package:
  name: adaptivemd-dev
  version: "0.2.0"

source:
#  git_url: ../../.git
  path: ../../

build:
  preserve_egg_dir: True
  number: 0

requirements:
  build:
    - python
    - setuptools
    - pyyaml

  run:
    - python
    - numpy
    - pyyaml
    - pymongo ==2.8
    - ujson

test:
  requires:
    - nose
    - nose-timer
    - python-coveralls
    - ipynbtest

  imports:
    - adaptivemd

about:
  home: https://github.com/markovmodel/adaptive-sampling
  license: LGPL 2.1 or later
  summary: 'A wrapper for radical.pilot to run adaptive MD'
